### PR TITLE
Port to Vaadin 8

### PR DESCRIPTION
**Pull request by willtemperley**
I just did a quick and brutal port to Vaadin 8.  I removed all deprecated methods.  It's not fully tested but the demo app shows most functionality remains intact.

### CODE REVIEW

**Comment by AemonAlgiz** [comment]
Hey Will,

You may want to consider uploading this to the Vaadin Directory. I looks like the original author no longer has the time to maintain this what-so-ever and exposing the updated code may make for more contributions.

**Comment by ahn** [comment]
Hi, sorry I've been absent. I'll take a look at this on the weekend and hopefully can upload Vaadin 8 version to the Directory.

**Comment by willtemperley** [comment]
@AemonAlgiz another option might be publishing to Maven Central or JCenter.  I've not done it before but it might provide the option of multiple authors per project.  For me this is a constant issue with the Vaadin setup, which is fine for single dev projects, but multiple authors or handing over ownership isn't officially supported.   Second, JCenter seems to provide better CI capabilities.

**Comment by ahn** [comment]
Version 0.8.15 of this add-on for Vaadin 8 is now at Vaadin Directory, thanks willtemperley.

I didn't test it very thoroughly, the basic stuff seems to work anyway.

**Pull request merged**
